version: '3.8'
services:
  backend:
    image: sebastianmr18/cv-optimizer-backend:latest
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src:ro
      - backend_node_modules:/app/node_modules
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    image: sebastianmr18/cv-optimizer-frontend:latest
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src:ro
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/_next/"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  backend_node_modules:
  frontend_node_modules:

networks:
  appnet:
    driver: bridge
