name: Build and Deploy Backend

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - feat/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./backend/package-lock.json
      
      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run unit tests
        run: npm run test
        working-directory: ./backend

      - name: Build
        run: npm run build
        working-directory: ./backend

      - name: Set Docker image tag
        id: tag
        run: |
          REF=${GITHUB_REF#refs/heads/}
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/develop ]]; then
            echo "TAG=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/feat/* ]]; then
            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's|/|-|g')
            echo "TAG=feature-${BRANCH_NAME}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=commit-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cv-optimizer-backend:${{ steps.tag.outputs.TAG }}