name: Build and Deploy Frontend

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - feat/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPRESS_BACKEND_URL: ${{ secrets.EXPRESS_BACKEND_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run unit tests
        run: npm run test
        working-directory: ./frontend

      - name: Run lint
        run: npm run lint
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend