name: Build and Deploy Frontend

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
      - feat/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPRESS_BACKEND_URL: ${{ secrets.EXPRESS_BACKEND_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run unit tests
        run: npm run test
        working-directory: ./frontend

      - name: Run lint
        run: npm run lint
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Set Docker image tag
        id: tag
        run: |
          REF=${GITHUB_REF#refs/heads/}
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/develop ]]; then
            echo "TAG=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/feat/* ]]; then
            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's|/|-|g')
            echo "TAG=feature-${BRANCH_NAME}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=commit-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:${{ steps.tag.outputs.TAG }}
