name: Build and Deploy Frontend

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - feat/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPRESS_BACKEND_URL: ${{ secrets.EXPRESS_BACKEND_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run unit tests
        run: npm run test
        working-directory: ./frontend

      - name: Run lint
        run: npm run lint
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Set Docker image tag
        id: tag
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == "develop" ]]; then
            echo "TAG=dev" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == feat/* ]]; then
            echo "TAG=feature-${BRANCH##feat/}" >> $GITHUB_OUTPUT
          else
            echo "TAG=${BRANCH}" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-app:${{ steps.tag.outputs.TAG }}